# Generated by Django 4.0.5 on 2022-07-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_or_room', models.IntegerField(default=1)),
                ('content', models.TextField(max_length=1000)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('sent', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('encrypted', models.BooleanField(default=False)),
                ('encryption_algorithm', models.CharField(choices=[(0, 'AES'), (1, 'RSA')], max_length=3)),
                ('destruct_timer', models.IntegerField(blank=True, default=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=32)),
                ('creation_date', models.DateTimeField()),
                ('private', models.BooleanField(default=False)),
                ('censored', models.BooleanField(default=False)),
            ],
        ),
    ]
