# Generated by Django 4.0.5 on 2022-07-07 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='start_date',
            new_name='creation_date',
        ),
    ]
