# Generated by Django 4.0.5 on 2022-07-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_chat_alter_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat_or_room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
