# Generated by Django 4.0.5 on 2022-07-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_chat_remove_message_chat_or_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delivered',
        ),
    ]
