# Generated by Django 4.0.5 on 2022-07-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_message_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
