# Generated by Django 4.0.5 on 2022-07-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=64)),
                ('forbidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_creator', to='website.profile')),
                ('keywords', models.ManyToManyField(related_name='watchlist_keywords', to='spybot.keyword')),
                ('rooms', models.ManyToManyField(related_name='watchlist_rooms', to='chat.room')),
                ('users', models.ManyToManyField(related_name='watchlist_profiles', to='website.profile')),
            ],
        ),
        migrations.CreateModel(
            name='InterceptedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intercept_date', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercepted_message_message', to='chat.message')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercepted_message_watchlist', to='spybot.watchlist')),
            ],
        ),
    ]
