# Generated by Django 4.0.5 on 2022-07-07 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_config_log'),
        ('chat', '0004_alter_message_chat_alter_message_room'),
        ('spybot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=64)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_message_message', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_message_user', to='website.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='InterceptedMessage',
        ),
    ]
